require('dotenv').config();

module.exports = {
    SMART_METER_USER_1: process.env.SMART_METER_USER_1,
    SMART_METER_PASS_1: process.env.SMART_METER_PASS_1,
    SMART_METER_USER_2: process.env.SMART_METER_USER_2,
    SMART_METER_PASS_2: process.env.SMART_METER_PASS_2,
    SMART_METER_USER_3: process.env.SMART_METER_USER_3,
    SMART_METER_PASS_3: process.env.SMART_METER_PASS_3,
    SMART_METER_USER_4: process.env.SMART_METER_USER_4,
    SMART_METER_PASS_4: process.env.SMART_METER_PASS_4,
    SMART_METER_USER_5: process.env.SMART_METER_USER_5,
    SMART_METER_PASS_5: process.env.SMART_METER_PASS_5,
    REPCARD_USER: process.env.REPCARD_USER,
    REPCARD_PASSWORD: process.env.REPCARD_PASSWORD,
    REPCARD_API_KEY: process.env.REPCARD_API_KEY,
    AURORA_LIGHTREACH_USER: process.env.AURORA_LIGHTREACH_USER,
    AURORA_LIGHTREACH_PASSWORD: process.env.AURORA_LIGHTREACH_PASSWORD,
    SUBCONTRACTOR_USER: process.env.SUBCONTRACTOR_USER,
    SUBCONTRACTOR_PASSWORD: process.env.SUBCONTRACTOR_PASSWORD
};
