const energy_providers = [
    'TXU',
    'Just Energy',
    'Reliant',
    'Direct Energy',
    'Cirro',
    'Chariot',
    'Green Mountain',
    'Gexa',
    'Iron Horse',
    'Clean sky',
    'Ambit Energy',
    'Amigo',
    '4Change Energy',
    'APG and E',
    'Good Charlie',
    'Pulse Power',
    'Rhythm',
    'Payless',
    'Xoom',
    'TriEagle Energy',
    'Discount Power',
    'Shell energy',
    'Ohmconnect',
    'snap energy',
    'Constellation Newenergy',
    'Champion Energy',
    'Stream Energy',
    'Ae texas',
    'bkv-bpp retail',
    'Snap energy',
    'ranchero power',
    'octopus',
    'frontier'
];
module.exports = energy_providers;