const energy_providers = [
    'TXU',
    'Just Energy',
    'Reliant',
    'Direct Energy',
    'Gexa',
    'Clean sky',
    'Ambit Energy',
    'Amigo',
    '4Change Energy',
    'Good Charlie',
    'Green Mountain',
    'Pulse Power',
    'Rhythm',
    'Cirro',
    'Payless',
    'Xoom',
    'Chariot',
    'TriEagle Energy',
    'Discount Power',
    'Constellation Newenergy',
    'Champion Energy',
    'Stream Energy',
    'Iron Horse',
    'Ae texas',
    'bkv-bpp retail',
    'octopus',
    'frontier',
];
module.exports = energy_providers;